[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

[build.environment]
  VITE_API_URL = "https://natures-basket-backend.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://natures-basket-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
