services:
  - type: web
    name: natures-basket-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /health
    healthCheckGracePeriod: 300
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: natures-basket-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://naturesbasketapp.netlify.app

databases:
  - name: natures-basket-db
    plan: free
    databaseName: natures-basket
